name = "mapvisor-api"
main = "src/index.ts"
compatibility_date = "2026-10-09"

[[d1_databases]]
binding = "DB"
database_name = "mapvisor-db"
database_id = "7b16307f-ee7b-479d-9f72-5361c1c1964d"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "mapvisor-lotes-media"

[vars]
APP_ORIGIN = "https://tupu-app.vercel.app"
R2_PUBLIC_BASE_URL = "https://pub-fdfecabd0dae455d9f03a8ac4be9eae3.r2.dev"
SESSION_COOKIE_NAME = "mapvisor_session"
